### ISSUE TITLE
Momentary flash of unstyled content.

### ISSUE THREAD

**Issue by SirRawlins** [sorry-app/status-bar#19]
For a brief moment the bar seems to load without any styles applied before kicking in,

My guess is the call to get the CSS script is asynchronous and and we should put some mech in place to watch for when the file is actually added to the DOM and loaded before we progress forward.

**Comment by jhabdas** [comment]
Alternative solution now available with Promise support, download parallels, chaining and script support. Requires browser to support ES6 and Fetch API.

https://github.com/jhabdas/fetch-inject

**Comment by SirRawlins** [comment]
Thanks Josh, I will be sure to check that out.
