### ISSUE TITLE
Ellipsis '...' omission on truncated text not working

### ISSUE THREAD

**Issue by SirRawlins** [sorry-app/status-bar#44]
We've had a customer suggest that when truncating the message text we should use a '...' omission at the end, to better indicate that there is more to read.

**Comment by SirRawlins** [comment]
This actually appears to be a bug, as we're using `text-overflow: ellipsis` which should already do this. Might be a flaw in the CSS, or a browser related bug - needs some investigation.

**Comment by warmfusion** [comment]
Browser Details:
* Google-Chrome on MacOS : Version 59.0.3071.115 (Official Build) (64-bit)

Interestingly on Firefox Android it shows the whole message.

**Comment by SirRawlins** [comment]
@warmfusion thanks for the pointer on the browser behaviour. Webkit vs. Gecko calculate if the text is overflowing in slightly different ways, some take padding/border into account while others don't, I've been caught with my pants down by that before.

I'll do some more thorough testing, it might just need some horizontal padding adding to the container or something.
