### ISSUE TITLE
Add option to unable to delete

### ISSUE THREAD

**Issue by tvb** [sorry-app/status-bar#52]
I want the status-bar to be shown fixed whenever there is a maintenance planned or ongoing without users being able to dismiss it (by clicking <img width="44" alt="screen shot 2018-06-03 at 17 28 01" src="https://user-images.githubusercontent.com/1263414/40888167-7aee7842-6753-11e8-87a9-8ebc56b2a352.png">)

Would you be able to add this?
ps. I know I could probably overwrite this with CSS to display-block:none but I'm not sure that is the proper way.

**Comment by SirRawlins** [comment]
@tvb absolutely, another good idea! You're right that you could use some CSS to hide the button, but for the sake of future-compatibility, it probably makes sense for us to add this as a feature.

I'm thinking of an extra data attribute, such as `data-dismissable="false"` or something like that, which when set removes the dismiss function.

**Comment by tvb** [comment]
That would be awesome! I am using CSS now, which works but it feels kinda hacky.

**Comment by SirRawlins** [comment]
@tvb I've just added this as a feature, there are [details in the README about how to use it](https://github.com/sorry-app/status-bar#prevent-readers-from-dismissing-notices).

You may need to clear your browser's cache to get it to pick up the changes.

**Comment by tvb** [comment]
Awesome!
