### ISSUE TITLE
truncate message on mobile

### ISSUE THREAD

**Issue by tvb** [sorry-app/status-bar#53]
Please truncate the message on mobile like we do on desktop too:
![img_1883c8a19c33-1](https://user-images.githubusercontent.com/1263414/40888236-51e6528e-6754-11e8-911d-e658cc90e64a.jpeg)

**Comment by SirRawlins** [comment]
@tvb yeah this is a very good point, otherwise, the plugin can become extremely dominant on mobile screens and hide the entire page. 

Leave it to me, I hope it'll only be some small CSS changes.

**Comment by SirRawlins** [comment]
@tvb I just released a fix for this, so the content is now truncated on mobile too. 👍
