### ISSUE TITLE
Support url missing target blank property

### ISSUE THREAD

**Issue by tvb** [sorry-app/status-bar#54]
This has nothing to do with the status-bar really but I wanted to post this anyway:

I have the following code on my maintenance page, however the support link does not have a `target="_blank"` property so my browser is blocking it for not allowing it to load insecure content. (I know it should be behind https but the service does not provide this option yet)
```
<li class="support-link-url">
    <!-- Conditionally append mailto: and tel: for appropriate actions. -->
    <a href="http://support.mydomain.com">http://support.mydomain.com</a>
</li>
```

Could you guys add a target blank to these links? Thanks!

**Comment by SirRawlins** [comment]
@tvb thanks for reporting this one. I've moved the issue over into our `theme-whitelabel` project as that's where the code for the error-page lives.

https://github.com/sorry-app/theme-whitelabel/issues/81

**Comment by tvb** [comment]
Thanks!
