### ISSUE TITLE
Correct version

### ISSUE THREAD

**Issue by tvb** [sorry-app/status-bar#60]
Browsing http://code.sorryapp.com/status-bar/4.4.1/status-bar.min.js states 
```
/* status-bar v4.4.0 | (c) 2018 SorryApp Ltd. |
```

Is this correct?

**Comment by SirRawlins** [comment]
Hi Tristan,

I'm out of the office for the day, but will take a closer look tomorrow.

I think it should read 4.4.1, but a bug in the build process updates the
banner comment one version behind what it should say.

It doesn't effect the functionality of the code at all.

Appreciate you pointing it out. 😋

**Comment by tvb** [comment]
@SirRawlins any update?

**Comment by SirRawlins** [comment]
@tvb sorry for the slow reply on this, my attention got drawn away onto other things. 

I wasn't able to tackle this the way I had hoped, but I have found a workaround which will do the trick. So new release 4.3.3 is now consistent, and the banner in the JS has the correct version.
