### ISSUE TITLE
Doesn't work in Edge

### ISSUE THREAD

**Issue by marek-dudas** [sorry-app/status-bar#64]
Seems the status-bar won't show in Edge (87.0.664.66, Chromium-based). Could be a CORS issue.

**Comment by SirRawlins** [comment]
@marek-dudas thanks for the report on this, I'll try and take a look, see if I can spot what's going on. 👍

**Comment by marek-dudas** [comment]
Actually, now I am not sure if it wasn't just my mistake, as it started working. But I got some CORS error at some point in Edge, although being it from localhost.

**Comment by SirRawlins** [comment]
O.k. that's good to know

I'll do some testing anyway, just to be sure. Thanks again for letting us
know.
